# Generated by Django 4.0.5 on 2022-09-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_chat_user1_alter_chat_user2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
    ]
