# Generated by Django 4.0.5 on 2022-09-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_read_user1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_read_user2',
            field=models.BooleanField(default=False),
        ),
    ]
