# Generated by Django 4.0.5 on 2022-09-02 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_chat_is_read_user1_chat_is_read_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_read_user1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='is_read_user2',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user2',
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_with_unread_messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unread_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
