# Generated by Django 4.0.5 on 2022-09-02 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_remove_chat_is_read_user1_remove_chat_is_read_user2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_with_unread_messages',
        ),
        migrations.AddField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='user2',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='chats_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
