# Generated by Django 4.0.5 on 2022-09-02 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_remove_chat_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_unread_messages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='unread_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
